storage: ./examples/verdaccio-example/registry
uplinks:
packages:
   '@*/*':
      # allow all users (including non-authenticated users) to read and
      # publish all packages
      access: '@all'
      publish: '@all'
   '**':
      # allow all users (including non-authenticated users) to read and
      # publish all packages
      access: '@all'
      publish: '@all'
log: { type: stdout, format: pretty, level: http }
listen:
  - 0.0.0.0:4873