name: cicd-feature

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
