name: cicd-release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # Checkout, setup node & python and build.
      - uses: ./.github/actions/common-build

      - name: Publish packages to GitHub Packages
        if: inputs.version-and-publish && runner.os == 'Linux'
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package vs-code extensions.
        if: inputs.version-and-publish && runner.os == 'Linux'
        run: yarn package:extensions

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: extensions/*/*.vsix
