name: feature

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

jobs:
  build-and-test:
    name: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-latest, macos-11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      # Checkout the code.
      - name: checkout # is needed to read the files on the root folder of the repo
        uses: actions/checkout@v4
      # Use the build action.
      - uses: ./.github/actions/build
      # Use the test action.
      - uses: ./.github/actions/test

  publish-test-report:
    name: Publish Test Report
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      # Checkout the code (needed for the action).
      - name: checkout # is needed to read the files on the root folder of the repo
        uses: actions/checkout@v4
      # Use the publish-test-report action.
      - uses: ./.github/actions/publish-test-report
